# Generated by Django 4.2.3 on 2023-08-02 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='members',
            field=models.ManyToManyField(related_name='shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
